/**
 * lib/streak.ts
 * Task 9 — Streak logic (Section 2.5)
 *
 * Called server-side after a session where the student answered ≥ 5 questions.
 * Reads / writes students.streak_count, students.last_active_date,
 * students.streak_freeze_remaining, and inserts into session_events.
 *
 * Returns the updated streak state so the client can show a milestone modal.
 */

import { createServerSupabaseClient } from "./supabase-server";

// Milestone days that trigger the confetti modal
export const STREAK_MILESTONES = [3, 7, 14, 30, 60, 100];

export interface StreakResult {
  newStreak: number;
  streakExtended: boolean;
  freezeUsed: boolean;
  isMilestone: boolean;
  milestoneDay: number | null;
}

/**
 * Process end-of-session streak update.
 *
 * @param studentId          UUID of the authenticated student
 * @param sessionId          UUID generated by the client for this session
 * @param questionsAnswered  total questions answered this session
 */
export async function processStreakUpdate(
  studentId: string,
  sessionId: string,
  questionsAnswered: number
): Promise<StreakResult> {
  const MIN_QUESTIONS = 5;

  const supabase = await createServerSupabaseClient();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = supabase as any;

  const { data: studentData, error } = await db
    .from("students")
    .select("streak_count, last_active_date, streak_freeze_remaining")
    .eq("id", studentId)
    .single();

  if (error || !studentData) {
    console.error("[streak] failed to fetch student data:", error?.message);
    return { newStreak: 0, streakExtended: false, freezeUsed: false, isMilestone: false, milestoneDay: null };
  }

  const student = studentData as {
    streak_count: number;
    last_active_date: string | null;
    streak_freeze_remaining: number;
  };

  const today = new Date();
  const todayStr = toDateString(today);
  const lastActive = student.last_active_date;

  // Already credited today — no change
  if (lastActive === todayStr) {
    return { newStreak: student.streak_count, streakExtended: false, freezeUsed: false, isMilestone: false, milestoneDay: null };
  }

  // Not enough questions this session
  if (questionsAnswered < MIN_QUESTIONS) {
    return { newStreak: student.streak_count, streakExtended: false, freezeUsed: false, isMilestone: false, milestoneDay: null };
  }

  const yesterdayStr = toDateString(subtractDays(today, 1));
  const twoDaysAgoStr = toDateString(subtractDays(today, 2));

  let newStreak = student.streak_count;
  let freezeUsed = false;
  let streakExtended = false;

  if (!lastActive) {
    // First ever session
    newStreak = 1;
    streakExtended = true;
  } else if (lastActive === yesterdayStr) {
    // Consecutive day — extend
    newStreak = student.streak_count + 1;
    streakExtended = true;
  } else if (lastActive === twoDaysAgoStr && student.streak_freeze_remaining > 0) {
    // Missed one day but has a freeze — use it
    newStreak = student.streak_count + 1;
    freezeUsed = true;
    streakExtended = true;
  } else {
    // Streak broken — reset to 1
    newStreak = 1;
    streakExtended = true;
  }

  const newFreezeRemaining = freezeUsed
    ? student.streak_freeze_remaining - 1
    : student.streak_freeze_remaining;

  // Persist
  await db
    .from("students")
    .update({
      streak_count: newStreak,
      last_active_date: todayStr,
      streak_freeze_remaining: newFreezeRemaining,
    })
    .eq("id", studentId);

  // Insert session_event if streak extended
  if (streakExtended) {
    await db.from("session_events").insert({
      student_id: studentId,
      session_id: sessionId,
      event_type: "streak_extended",
      event_data: {
        new_streak: newStreak,
        freeze_used: freezeUsed,
        questions_answered: questionsAnswered,
      },
    });
  }

  const isMilestone = STREAK_MILESTONES.includes(newStreak);
  const milestoneDay = isMilestone ? newStreak : null;

  return { newStreak, streakExtended, freezeUsed, isMilestone, milestoneDay };
}

// ── Helpers ────────────────────────────────────────────────────────────────

function toDateString(date: Date): string {
  return date.toISOString().slice(0, 10);
}

function subtractDays(date: Date, days: number): Date {
  const d = new Date(date);
  d.setDate(d.getDate() - days);
  return d;
}
