#!/usr/bin/env npx ts-node
/**
 * generate-seed.ts
 *
 * Reads topic_seed_data_v2.json and outputs supabase/seed.sql containing:
 *  1. INSERT statements for public.topics   (68 math topics, Phase 1 MVP)
 *  2. INSERT statements for public.topic_dependencies  (from prerequisites[])
 *
 * Usage:
 *   npx ts-node scripts/generate-seed.ts
 *   # or: node --loader ts-node/esm scripts/generate-seed.ts
 */

import * as fs from "fs";
import * as path from "path";

// ─── Types ───────────────────────────────────────────────────────────────────

interface RawTopic {
  id: string;
  standard: string;
  name: string;
  description: string;
  grade: number;
  subject: string;
  difficulty_range: [number, number];
  question_formats: string[];
  prerequisites: string[];
  unlocks: string[];
}

interface SeedData {
  subjects: {
    math: Record<string, RawTopic[]>;
    [key: string]: unknown;
  };
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Escape a string for SQL single-quote literals. */
function sqlStr(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** Render a string[] as a Postgres text[] literal, e.g. ARRAY['a','b']. */
function sqlTextArray(arr: string[]): string {
  if (arr.length === 0) return "ARRAY[]::text[]";
  return `ARRAY[${arr.map(sqlStr).join(", ")}]`;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

const ROOT = path.resolve(__dirname, "..");
const JSON_PATH = path.join(ROOT, "supabase", "seed", "topic_seed_data_v2.json");
const OUT_PATH = path.join(ROOT, "supabase", "seed.sql");

const raw = fs.readFileSync(JSON_PATH, "utf-8");
const data: SeedData = JSON.parse(raw);

const mathByGrade = data.subjects.math;

// Flatten all math topics in grade order
const allTopics: RawTopic[] = [];
for (const gradeKey of Object.keys(mathByGrade).sort()) {
  allTopics.push(...mathByGrade[gradeKey]);
}

console.log(`Found ${allTopics.length} math topics.`);

// ─── Build SQL ───────────────────────────────────────────────────────────────

const lines: string[] = [
  "-- ScienceQuest — Phase 1 Seed Data",
  "-- Generated by scripts/generate-seed.ts",
  "-- 68 math topics (Grades 1–8) from topic_seed_data_v2.json",
  "-- Phase 1 MVP: math subject only.",
  "",
  "-- Topics ─────────────────────────────────────────────────────────",
  "insert into public.topics (id, standard, name, description, grade, subject, diff_min, diff_max, question_formats)",
  "values",
];

const topicValues = allTopics.map((t, i) => {
  const [diffMin, diffMax] = t.difficulty_range;
  const comma = i < allTopics.length - 1 ? "," : "";
  return (
    `  (${sqlStr(t.id)}, ${sqlStr(t.standard)}, ${sqlStr(t.name)}, ` +
    `${sqlStr(t.description)}, ${t.grade}, ${sqlStr(t.subject)}, ` +
    `${diffMin}, ${diffMax}, ${sqlTextArray(t.question_formats)})${comma}`
  );
});

lines.push(...topicValues);
lines.push("on conflict (id) do nothing;");
lines.push("");

// ─── topic_dependencies ───────────────────────────────────────────────────────

// Build a set of all valid topic IDs for referential safety
const validIds = new Set(allTopics.map((t) => t.id));

const depRows: Array<{ topic_id: string; prereq_id: string }> = [];

for (const t of allTopics) {
  for (const prereqId of t.prerequisites) {
    if (!validIds.has(prereqId)) {
      console.warn(
        `  ⚠ Skipping dependency ${t.id} → ${prereqId}: prerequisite not in seed set`
      );
      continue;
    }
    depRows.push({ topic_id: t.id, prereq_id: prereqId });
  }
}

if (depRows.length > 0) {
  lines.push(
    "-- Topic dependencies ────────────────────────────────────────────"
  );
  lines.push(
    "insert into public.topic_dependencies (topic_id, prerequisite_topic_id)"
  );
  lines.push("values");

  const depValues = depRows.map((d, i) => {
    const comma = i < depRows.length - 1 ? "," : "";
    return `  (${sqlStr(d.topic_id)}, ${sqlStr(d.prereq_id)})${comma}`;
  });

  lines.push(...depValues);
  lines.push("on conflict do nothing;");
  lines.push("");
} else {
  lines.push(
    "-- No topic_dependencies rows (all prerequisites[] arrays are empty in Phase 1 math topics)."
  );
  lines.push("");
}

// ─── Write output ─────────────────────────────────────────────────────────────

const sql = lines.join("\n");
fs.writeFileSync(OUT_PATH, sql, "utf-8");

console.log(`✓ Wrote ${OUT_PATH}`);
console.log(`  Topics inserted:      ${allTopics.length}`);
console.log(`  Dependencies inserted: ${depRows.length}`);
