#!/usr/bin/env node
/**
 * generate-seed.js
 * Plain Node.js version of generate-seed.ts (no TypeScript toolchain required).
 * Reads topic_seed_data_v2.json → writes supabase/seed.sql
 *
 * Usage:  node scripts/generate-seed.js
 */

const fs   = require("fs");
const path = require("path");

function sqlStr(v)         { return "'" + v.replace(/'/g, "''") + "'"; }
function sqlTextArray(arr) {
  if (!arr.length) return "ARRAY[]::text[]";
  return "ARRAY[" + arr.map(sqlStr).join(", ") + "]";
}

const ROOT     = path.resolve(__dirname, "..");
const JSON_PATH = path.join(ROOT, "supabase", "seed", "topic_seed_data_v2.json");
const OUT_PATH  = path.join(ROOT, "supabase", "seed.sql");

const data         = JSON.parse(fs.readFileSync(JSON_PATH, "utf-8"));
const mathByGrade  = data.subjects.math;

// Flatten all math topics in grade order
const allTopics = [];
for (const g of Object.keys(mathByGrade).sort()) allTopics.push(...mathByGrade[g]);
console.log(`Found ${allTopics.length} math topics.`);

// ─── topics INSERT ────────────────────────────────────────────────────────────

const lines = [
  "-- ScienceQuest — Phase 1 Seed Data",
  "-- Generated by scripts/generate-seed.js",
  "-- 68 math topics (Grades 1–8) from topic_seed_data_v2.json",
  "-- Phase 1 MVP: math subject only.",
  "",
  "-- Topics ──────────────────────────────────────────────────────────",
  "insert into public.topics (id, standard, name, description, grade, subject, diff_min, diff_max, question_formats)",
  "values",
];

allTopics.forEach((t, i) => {
  const [dMin, dMax] = t.difficulty_range;
  const comma        = i < allTopics.length - 1 ? "," : "";
  lines.push(
    "  (" +
    [sqlStr(t.id), sqlStr(t.standard), sqlStr(t.name), sqlStr(t.description),
     t.grade, sqlStr(t.subject), dMin, dMax, sqlTextArray(t.question_formats)].join(", ") +
    ")" + comma
  );
});

lines.push("on conflict (id) do nothing;", "");

// ─── topic_dependencies INSERT ────────────────────────────────────────────────

const validIds = new Set(allTopics.map(t => t.id));
const deps     = [];

for (const t of allTopics) {
  for (const prereq of t.prerequisites) {
    if (validIds.has(prereq)) {
      deps.push({ topic_id: t.id, prereq_id: prereq });
    } else {
      console.warn(`  ⚠ Skipping dep ${t.id} → ${prereq}: not in Phase 1 math set`);
    }
  }
}

if (deps.length) {
  lines.push("-- Topic dependencies ───────────────────────────────────────────────");
  lines.push("insert into public.topic_dependencies (topic_id, prerequisite_topic_id)");
  lines.push("values");
  deps.forEach((d, i) => {
    const comma = i < deps.length - 1 ? "," : "";
    lines.push("  (" + sqlStr(d.topic_id) + ", " + sqlStr(d.prereq_id) + ")" + comma);
  });
  lines.push("on conflict do nothing;", "");
} else {
  lines.push("-- No topic_dependencies rows (all prerequisites[] empty in Phase 1 math set).", "");
}

// ─── Write ────────────────────────────────────────────────────────────────────

fs.writeFileSync(OUT_PATH, lines.join("\n"), "utf-8");
console.log(`✓ Wrote ${OUT_PATH}`);
console.log(`  Topics:       ${allTopics.length}`);
console.log(`  Dependencies: ${deps.length}`);
